export const CATEGORY_CHECKED_UNCHECKED = "CATEGORY_CHECKED"
export const COUNTRY_CHECKED_UNCHECKED = "COUNTRY_CHECKED"
export const HIDE_FILTER_CC = "HIDE_FILTER_CC"
export const SHOW_FILTER_CC = "SHOW_FILTER_CC"


export const FETCH_DATA_USING_CHECKBOXES_AND_FILTER = "FETCH_DATA_USING_CHECKBOXES_AND_FILTER" 
